### ISSUE TITLE
Loopback model definition is not adding foreign key relation in database table

### ISSUE THREAD

**Issue by fusionstrings** [loopbackio/loopback-connector-mysql#16]
It seems loopback is not adding foreign key constraint in MySQL Database table as per model definition. The same questions is asked in stackoverflow.

http://stackoverflow.com/questions/20877265/loopback-model-definition-is-not-adding-foreign-key-relation-in-database-table

I am not sure I am doing it wrong or it is by design of loopback so I am duplicating the same here.

I am using loopback for API design and data modeling. I am using MySQL as my database. Although my API rest URL successfully returns results e.g. `/states/{id}/cities`. I have following model but it seems no foreign key relation is added. Following are my model definition.

```
"state": {
  "options": {
    "relations": {
      "cities": {
        "type": "hasMany",
        "model": "city",
        "foreignKey": "stateId"
      }
    }
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "public": true,
  "dataSource": "db",
  "plural": "states"
},
"city": {
  "options": {
    "relations": {
      "state": {
        "type": "belongsTo",
        "model": "state",
        "foreignKey": "stateId"
      }
    }
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "public": true,
  "dataSource": "db",
  "plural": "cities"
}
```

and below is screenshot of city table. 
![enter image description here](http://i.stack.imgur.com/yGqOF.png)

And following is State table screenshot.
![enter image description here](http://i.stack.imgur.com/OH1na.png)

I may be doing it wrong here. Looking forward for any pointers.

**Comment by EmileSpecs** [comment]
For anyone else that needs this, you can check out my fork:
https://github.com/EmileSpecs/loopback-connector-mysql/tree/feature/foreign-key-migration

It just supports "belongsTo" relations at the moment since those are all I needed. Shouldn't be to difficult to add other relevant relationship types.

It makes sense to me that the database takes care of relational integrity of data and it saves a lot of code to not have to worry about cascading your deletions to linked models.

**Comment by qaiser110** [comment]
Since I use automigrate a lot for my tests, I've added the following code after automigrate to add indexes after table creation

let sql = 'ALTER TABLE quote add constraint fk_book foreign key (book_id) REFERENCES book (id);'
Quote.dataSource.connector.query(sql, done);

**Comment by josefd8** [comment]
Hi @fusionstrings , just stumble upon this same problem and I was wondering "what am I doing wrong?" but yes, it appears that loopback is not adding the foreign key constrains in the RDB on migrate. I wanted to ask you: what approach did you finally use? did you add the constrains yourself manually? I'm finding very cumbersome having to add extra logic in the models controller to add the proper reference to the owner model id

**Comment by fusionstrings** [comment]
@josefd8 Yes it's cumbersome but that's the workaround I'd to adopt. As of not it's been ages since I'd used loopback so can't say much.

**Comment by netojose** [comment]
This can help:

https://www.npmjs.com/package/loopback-mysql-referential-integrity-component

**Comment by dienluong** [comment]
This is supported by the newer mysql-connector.  The information is buried in the documentation.  See https://github.com/strongloop/loopback-connector-mysql/issues/294

**Comment by FournetThomas** [comment]
Does it have any impact on performance when doing complex queries ?
