### ISSUE TITLE
Filter is not applied on count()

### ISSUE THREAD

**Issue by marmarosi** [loopbackio/loopback-connector-mysql#35]
Using Model.count([filter], callback), filter settings do not appear in MySQL's SELECT COUNT(*) statement.

**Comment by jamesw6811** [comment]
+1 this needs better documentation

**Comment by superkhau** [comment]
@marmarosi Please create a new issue with specifics (ie. why the docs are bad, what do you need to see, which parts need improvement, etc) so that we can get it assigned to @crandmck to get it fixed. We do not take action on comments in closed issues.

**Comment by superkhau** [comment]
>The count() method only takes the where clause instead of the filter

@raymondfeng We should probably add an alias functions that take a filter and do the same thing. Probably something to add for my LB3 juggler proposal.

**Comment by cfjedimaster** [comment]
+1 to needing this better documented

**Comment by crandmck** [comment]
Hey @cfjedimaster I tried to clarify [Where clause for queries](https://docs.strongloop.com/display/APIC/Where+filter#Wherefilter-Whereclauseforqueries) and [Where clause for other methods](https://docs.strongloop.com/display/APIC/Where+filter#Wherefilter-Whereclauseforothermethods) about the where clause for `count()`.   LMK if it can be clarified further or somewhere else.

**Comment by raymondfeng** [comment]
@crandmck The `where` object is the same for all methods. What's different is that some methods (such as count) take a `where` object directly while others (such as find) take a `filter` that can contain `where`. The `filter` object also supports other child items such as `limit` and `order`.

**Comment by crandmck** [comment]
OK, but we went through this whole fire-drill some time ago to describe the difference in the syntax (which we document and give examples of) because sometimes the where clause is wrapped in `{where: ... }` and sometimes not.

  The docs say:
> For query methods such as find(), findOrCreate(), or findOne(), use `{where: {property: value}}`

and

> ... for methods that update and delete (and count()), don't wrap the where clause in a `{ where : ... }`, ... so use `{property: value}`

I just tested that myself and it seems to be accurate.

**Comment by raymondfeng** [comment]
You ar

**Comment by cfjedimaster** [comment]
It kinda makes sense now - to be honest, I probably would have stopped reading before "Where clause for other methods". Honestly, it seems weird and arbitrary a bit as well - but I'm still new to LB. 

One suggestion. The first doc section includes REST API examples, the second does. It should, shouldn't it?

**Comment by philip13** [comment]
> The count() method only takes the `where` clause instead of the `filter`. Your REST URL should be:
> 
> [http://localhost:3000/api/malts/count?where[maltName][like]=%25ap%25](http://localhost:3000/api/malts/count?where%5BmaltName%5D%5Blike%5D=%25ap%25)

I don't know how to count with two filters, it works only with one, can you help me please?
I try with that: 
`http://localhost:3000/Users/count?where[profileC][ilike]=%25Designer%25[additionalSkillsC][ilike]=%25figma%25`

**Comment by mathias22osterhagen22** [comment]
> > The count() method only takes the `where` clause instead of the `filter`. Your REST URL should be:
> > [http://localhost:3000/api/malts/count?where[maltName][like]=%25ap%25](http://localhost:3000/api/malts/count?where%5BmaltName%5D%5Blike%5D=%25ap%25)
> 
> I don't know how to count with two filters, it works only with one, can you help me please?
> I try with that:
> `http://localhost:3000/Users/count?where[profileC][ilike]=%25Designer%25[additionalSkillsC][ilike]=%25figma%25`

Hello dear, 
I was in the same case as you.

To apply multiple filters just add a "and" property with an array of your "conditions"

```js
{
   "or":[
      {
         "statusId":"5"
      },
      {
         "statusId":"6"
      },
      {
         "statusId":"7"
      }
   ]
}
```

**Comment by deluca-mike** [comment]
multiple filters for count is either poorly documented, poorly conceived, incorrectly implemented, or some combination of the above.
