### ISSUE TITLE
MySQL regex syntax does not respect the `i` flag

### ISSUE THREAD

**Issue by ernie58** [loopbackio/loopback-connector-mysql#352]
# Description/Steps to reproduce
```javascript
let reg = new RegExp(`/John/`, 'i');
Person.find ({
    where: {
        {firstName: {regexp: reg}}
    }
});
```
# Expected result
Expected: It should search case insensitive without warnings
Actual: It searches case insensitive and gives the warning   
```MySQL regex syntax does not respect the `i` flag```

So the results are as expected, but a warning is thrown, which pollutes the log

# Additional information
I think, as Mysql is case insensitive by default, the warning is not necessary

**Comment by ernie58** [comment]
I would suggest deleting this line:
https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L555

**Comment by shadyanwar** [comment]
@ernie58 still facing this? Why not reopen the issue?

**Comment by TomDobbelaere** [comment]
While cleaning up the logs we are still facing this issue.

@ernie58 Can you leave a comment so the issue is reopened?

**Comment by Lambdac0re** [comment]
The line is still there...
