### ISSUE TITLE
Migrate: Weird behaviour when the MySQL server hosts other databases

### ISSUE THREAD

**Issue by Salketer** [loopbackio/loopback-connector-mysql#426]
## Steps to reproduce

Get the loopback 4 TODO example working.
Create a second database alongside the data used by the todo app.
In your new database, create a dummy table that you'll need in next step.
In your new database, create a table named "Todo" and add foreign keys to it.
Run migrate on the app.

## Current Behavior

Error: ER_CANT_DROP_FIELD_OR_KEY
"Can't DROP 'fk_name_you_created'; check that column/key exists"

## Expected Behavior

Should not try to drop the foreign key as it does not exist...

## Link to reproduction sandbox

Sorry, can't recreate it and provide example...

## Additional information

node -e 'console.log(process.platform, process.arch, process.versions.node)'
And
npm ls --prod --depth 0 | grep loopback
Produce errors on my machine... So hmm...

I'm on W10, 64bit, node is v14.4.0
Using loopback-connector-mysql@5.4.4

The culprit seems to be the query built by https://github.com/strongloop/loopback-connector-mysql/blob/928cb4990ba5f6f31d42a88e2b0bd2ec457d1c8a/lib/discovery.js#L241

The log shows this:
```
loopback:connector:mysql 
SQL: SELECT table_schema AS "fkOwner", constraint_name AS "fkName", table_name AS "fkTableName", column_name AS "fkColumnName", ordinal_position AS "keySeq", referenced_table_schema AS "pkOwner", 'PRIMARY' AS "pkName", referenced_table_name
AS "pkTableName", referenced_column_name AS "pkColumnName" FROM information_schema.key_column_usage WHERE constraint_name!='PRIMARY' AND POSITION_IN_UNIQUE_CONSTRAINT IS NOT NULL AND table_name='Todo', 
params: [] 
```
For some reasons it does not receive the schema name...

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by Salketer** [comment]
The problem is likely to come from somewhere else...

My datasource configuration was not setting a database key, only the URL connection scheme was defined:

```
{
      name: 'main',
      connector: 'mysql',
      url: 'mysql://root:root@192.168.99.105:3306/ssc2'
}
```


```
{
      name: 'main',
      connector: 'mysql',
      url: 'mysql://root:root@192.168.99.105:3306/ssc2',
     database:'ssc2' // WORKS
}
```

When setting the database name in the config object this started working fine and the logs show the table_schema being used in the previous query...

Shouldn't the connector automatically define its database name if it is included in the connection url?

**Comment by agnes512** [comment]
If you already have tables defined in the db, you don't need to run the migration script. Could you share your model definitions? I think the problem might happen when the migration script tries to drop the table.

**Comment by Salketer** [comment]
It really is when it tries to drop a foreign key because the model has none
defined.

**Comment by Salketer** [comment]
This problem has caused us, again, a great loss of time debugging things for no reasons. If this is open to PR, I'd gladly submit a proposal to correct this.

**Comment by agnes512** [comment]
@Salketer sorry that I've been busy and don't have time to take a closer look at the issue. And yes! feel free to submit a PR and ping me for review. Thanks!

**Comment by emonddr** [comment]
@Salketer , please take a look at docs/site/tutorials/todo-list/todo-list-tutorial-sqldb.md ( in this PR I have not landed yet https://github.com/strongloop/loopback-next/pull/6642 ) It covers the Todo example using mysql. Perhaps it can help you.
