### ISSUE TITLE
AWS EC2 LoopBack Keep Connecting to 127.0.0.1 Even Already Specified RDS Endpoint

### ISSUE THREAD

**Issue by zaimazhar97** [loopbackio/loopback-connector-mysql#452]
## Steps to reproduce

- Fill your RDS credentials through your .env
```
MYSQL_HOST=db-instance.db-code.db-zone-1.rds.amazonaws.com
MYSQL_DB=db-name
MYSQL_USERNAME=db-user
MYSQL_PASSWORD=db-pass
```
- Datasource
```
const config = {
  name: 'mysql',
  connector: 'mysql',
  url: '',
  host: process.env.MYSQL_HOST,
  port: 3306,
  user: process.env.MYSQL_USERNAME,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DB,
};
```
- Run `sudo npm run pretest && npm run migrate`
- Follow this deployment [tutorial](https://loopback.io/doc/en/lb4/deploying-with-pm2-and-nginx.html)
- Upon start, go to your specified reverse-proxy link. You should receive `502 Bad Gateway`.

![image](https://user-images.githubusercontent.com/54124001/129428684-f5970ddb-efa4-48c2-b4dd-a861750b21eb.png)
- Accessing the error in your `~/.pm2/logs` will show as below

![image](https://user-images.githubusercontent.com/54124001/129428758-0b43167f-27a0-43cb-9f01-4f1f9d0696ae.png)

## Expected Behavior

- Successfully connected to LoopBack

## Additional information
- Cloud Provider: AWS EC2
- OS: Ubuntu 20.04
- Database Server: RDS MySQL 5.7.34
- Node: 14.17.0
- npm: 7.20.5
- @loopback/boot: ^2.5.1
- @loopback/core: ^2.15.0
- loopback-connector-mysql: ^5.4.4 
- @types/dotenv: ^8.2.0

MongoDB and Redis were running locally so it doesn't seem to be a problem even by filling the credentials through .env.

**Comment by mrmodise** [comment]
Did you test that dotenv is indeed pulling the environment variables? you could console.log the config in the constructor of the datasource to verify this

**Comment by zaimazhar97** [comment]
@mrmodise Good idea will try it definitely. Will respond after I have done some tests. Thank you.

**Comment by zaimazhar97** [comment]
Hi, sorry for the late update. I managed to get it working but I need to blatantly paste the credential inside the datasource. It worked yes, but it is very daunting when I have to switch between development, staging, and production.

So I did the `console.log` inside the mysql datasource constructor and it shows this _before_ the server starts. It returned the correct values.

```js
const config = {
  name: 'mysql',
  connector: 'mysql',
  url: process.env.MYSQL_URL,
  password: process.env.MYSQL_PASSWORD,
};
```

![1](https://user-images.githubusercontent.com/54124001/133956224-d702cf83-32e6-473a-b414-2c9314f646c7.png)

However, after the server booted. Opening the `pm2 logs`, it shows this.

![2](https://user-images.githubusercontent.com/54124001/133956424-08fc3319-3bbc-4736-a716-bfe67a96b2c3.png)

Currently, I had to stick with pasting the credential directly into the datasource and it s running fine.

```js
const config = {
  name: 'mysql',
  connector: 'mysql',
  url: 'mysql://admin:pass@rds-db.rds-code.rds-timezone.rds.amazonaws.com:3306/db',
  password: 'pass'
};
```

![image](https://user-images.githubusercontent.com/54124001/133956514-bfc02062-92a8-43cb-985a-401b2d1e8526.png)

**Comment by mrmodise** [comment]
ah! i think the issue is with ``dotenv``. How are you bootstrapping it?

**Comment by zaimazhar97** [comment]
Hi. I am not sure what you mean by bootstrapping it. If it meant how I start the application. I do this;

 `npm run pretest && npm run migrate && npm run pm2-start`
```js
"pm2-start": "pm2 start ecosystem.config.js --env production",
"pm2-stop": "pm2 stop ecosystem.config.js --env production"

// ecosystem.config.js
module.exports = {
  apps: [
    {
      name: 'app-dev',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
  ],
};

// .env
NODE_ENV=development
MYSQL_URL=
MYSQL_HOST=
MYSQL_DB=
MYSQL_USERNAME=
MYSQL_PASSWORD=
```
At this point, I started to believe it has something to do with pm2 or Nginx. Just that I don't know where to start.

**Comment by zaimazhar97** [comment]
Hi.

I got it working now. After adding `node_args : '-r dotenv/config',`

```js
module.exports = {
  apps: [
    {
      name: 'app',
      script: 'dist/index.js',
      node_args : '-r dotenv/config',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
  ],
};
```
