### ISSUE TITLE
Add support for nodejs v18 and mysql v8

### ISSUE THREAD

**Issue by samarpanB** [loopbackio/loopback-connector-mysql#477]
Currently this connector doesn't support mysql version 8. Now in order to support nodejs v18, support for mysql v8 has become mandatory as the [setup-mysql action](https://github.com/ankane/setup-mysql) will fail in CI without it.

**Comment by samarpanB** [comment]
Here are more details - https://github.com/loopbackio/loopback-connector-mysql/pull/476#discussion_r1056980407

**Comment by wesleymilan** [comment]
Any update?

**Comment by tokidoki11** [comment]
FYI Node 16 support will be ending in September 11th, 2023

**Comment by samarpanB** [comment]
We are working on it. However, if community wants to contribute, feel free.

**Comment by samarpanB** [comment]
We need to upgrade to mysql2 as well, since, mysql package has Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client issue. This problem occurs while using MySQL dependency. Currently, MySQL 8.0 default authentication plugin caching sha2 password is not supported by the mysql npm package.
